version: '2'

services:
  webpack:
    build: 
      context: .
      dockerfile: docker.nodejs
    image: my-webpack
    container_name: react-webpack
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
